<#
.SYNOPSIS
  Validation called by scripts/ai-pipeline.ps1 after every implementer round (core file of ai-pipeline).
.DESCRIPTION
  Built-in checks, on changed files only:
    *.py   -> Python syntax (ast.parse, writes no __pycache__)
    *.ps1  -> PowerShell parse errors + ASCII only (Windows PowerShell 5.1 reads BOM-less UTF-8 as ANSI)
    *.json -> ConvertFrom-Json
    .ai/required-anchors.txt (optional) -> line prefixes that must stay in the named files
  Project checks: if .ai/checks.ps1 exists it is run with -Root, -ChangedFilesPath and -Full.
  It prints lines 'PASS  ...', 'FAIL  ...', 'SKIP  ...' and exits non-zero on failure.
  Last output line: VALIDATION_STATUS=PASS|FAIL|NOT_RUN. Exit code 0 unless FAIL.
  Do not edit this file per project; it is replaced by install.ps1 -Update. Use .ai/checks.ps1.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Root,
    [string]$ChangedFilesPath,
    [switch]$Full
)
Set-StrictMode -Version 2
$ErrorActionPreference = 'Stop'
$utf8 = New-Object System.Text.UTF8Encoding $false

$script:ran = 0
$script:failed = 0
function Pass([string]$m) { $script:ran++; Write-Output "PASS  $m" }
function Fail([string]$m) { $script:ran++; $script:failed++; Write-Output "FAIL  $m" }
function Skip([string]$m) { Write-Output "SKIP  $m" }

$changed = @()
if ($ChangedFilesPath -and (Test-Path -LiteralPath $ChangedFilesPath)) {
    # lines: <status><TAB><path> as written by ai-pipeline.ps1; deleted files are not checked
    foreach ($line in [IO.File]::ReadAllLines($ChangedFilesPath, $utf8)) {
        if (-not $line.Trim()) { continue }
        $parts = $line -split "`t"
        if ($parts[0] -like 'D*') { continue }
        $changed += $parts[-1]
    }
}
Write-Output ("changed files considered: {0}" -f $changed.Count)

$python = $null
try { $python = (Get-Command python -ErrorAction Stop).Source } catch { }

foreach ($rel in $changed) {
    $abs = Join-Path $Root $rel
    if (-not (Test-Path -LiteralPath $abs)) { continue }
    $ext = [IO.Path]::GetExtension($rel).ToLowerInvariant()
    switch ($ext) {
        '.py' {
            if (-not $python) { Skip "$rel (python not found)"; break }
            $prev = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
            $out = & $python -c "import ast,sys;[ast.parse(open(p,encoding='utf-8').read(),p) for p in sys.argv[1:]]" $abs 2>&1
            $code = $LASTEXITCODE; $ErrorActionPreference = $prev
            if ($code -eq 0) { Pass "$rel python syntax" } else { Fail ("$rel python syntax: " + (($out | ForEach-Object { "$_" }) -join ' | ')) }
        }
        '.ps1' {
            $tokens = $null; $errs = $null
            [void][System.Management.Automation.Language.Parser]::ParseFile($abs, [ref]$tokens, [ref]$errs)
            if ($errs -and $errs.Count -gt 0) {
                Fail ("$rel PowerShell parse: " + (($errs | ForEach-Object { "line $($_.Extent.StartLineNumber): $($_.Message)" }) -join ' | '))
            } else { Pass "$rel PowerShell parse" }
            $bytes = [IO.File]::ReadAllBytes($abs)
            $bad = 0; foreach ($b in $bytes) { if ($b -gt 127) { $bad++ } }
            if ($bad -gt 0) { Fail "$rel contains $bad non-ASCII bytes (.ps1 files must be ASCII only for PowerShell 5.1)" } else { Pass "$rel ASCII only" }
        }
        '.json' {
            try { [void]([IO.File]::ReadAllText($abs, $utf8) | ConvertFrom-Json); Pass "$rel JSON parse" }
            catch { Fail "$rel JSON parse: $($_.Exception.Message)" }
        }
        default { }
    }
}

# Required anchors (UTF-8 file, so non-ASCII text stays out of this script).
# Line format: <file>|<prefix>   or   <file>|#count|<prefix>|<minimum>
$anchorFile = Join-Path $Root '.ai\required-anchors.txt'
if (Test-Path -LiteralPath $anchorFile) {
    $rules = [IO.File]::ReadAllLines($anchorFile, $utf8) | Where-Object { $_.Trim() -and -not $_.StartsWith('#') }
    $cache = @{}
    foreach ($rule in $rules) {
        $p = $rule -split '\|'
        $file = $p[0]
        if ($changed -notcontains $file) { continue }
        $abs = Join-Path $Root $file
        if (-not (Test-Path -LiteralPath $abs)) { Fail "$file missing (required by .ai/required-anchors.txt)"; continue }
        if (-not $cache.ContainsKey($file)) { $cache[$file] = [IO.File]::ReadAllLines($abs, $utf8) }
        $lines = $cache[$file]
        if ($p.Count -ge 4 -and $p[1] -eq '#count') {
            $prefix = $p[2]; $need = [int]$p[3]
            $n = @($lines | Where-Object { $_.StartsWith($prefix, [StringComparison]::Ordinal) }).Count
            if ($n -ge $need) { Pass "$file has $n lines starting with '$prefix' (need >= $need)" }
            else { Fail "$file has $n lines starting with '$prefix' (need >= $need)" }
        } else {
            $prefix = $p[1]
            $hit = @($lines | Where-Object { $_.StartsWith($prefix, [StringComparison]::Ordinal) }).Count
            if ($hit -gt 0) { Pass "$file anchor '$prefix'" } else { Fail "$file anchor missing: '$prefix'" }
        }
    }
}

# Project checks
$hook = Join-Path $Root '.ai\checks.ps1'
if (Test-Path -LiteralPath $hook) {
    Write-Output '--- .ai/checks.ps1'
    $hArgs = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $hook, '-Root', $Root)
    if ($ChangedFilesPath) { $hArgs += @('-ChangedFilesPath', $ChangedFilesPath) }
    if ($Full) { $hArgs += '-Full' }
    $prev = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
    $out = & (Join-Path $PSHOME 'powershell.exe') @hArgs 2>&1
    $code = $LASTEXITCODE; $ErrorActionPreference = $prev
    $hookFails = 0
    foreach ($l in $out) {
        $s = "$l"
        Write-Output $s
        if ($s.StartsWith('PASS  ')) { $script:ran++ }
        elseif ($s.StartsWith('FAIL  ')) { $script:ran++; $script:failed++; $hookFails++ }
    }
    if ($code -ne 0 -and $hookFails -eq 0) { Fail ".ai/checks.ps1 exited with code $code" }
}

if ($script:failed -gt 0) { $status = 'FAIL' } elseif ($script:ran -gt 0) { $status = 'PASS' } else { $status = 'NOT_RUN' }
Write-Output "checks run: $($script:ran), failed: $($script:failed)"
Write-Output "VALIDATION_STATUS=$status"
if ($status -eq 'FAIL') { exit 1 } else { exit 0 }
